// Compact India address data for checkout (replaces the 8 MB country-state-city
// world dataset). Keys are ISO 3166-2:IN state codes.

export const INDIAN_STATES = [
  { value: "AN", label: "Andaman and Nicobar Islands" },
  { value: "AP", label: "Andhra Pradesh" },
  { value: "AR", label: "Arunachal Pradesh" },
  { value: "AS", label: "Assam" },
  { value: "BR", label: "Bihar" },
  { value: "CH", label: "Chandigarh" },
  { value: "CG", label: "Chhattisgarh" },
  { value: "DD", label: "Dadra and Nagar Haveli and Daman and Diu" },
  { value: "DL", label: "Delhi" },
  { value: "GA", label: "Goa" },
  { value: "GJ", label: "Gujarat" },
  { value: "HR", label: "Haryana" },
  { value: "HP", label: "Himachal Pradesh" },
  { value: "JK", label: "Jammu and Kashmir" },
  { value: "JH", label: "Jharkhand" },
  { value: "KA", label: "Karnataka" },
  { value: "KL", label: "Kerala" },
  { value: "LA", label: "Ladakh" },
  { value: "LD", label: "Lakshadweep" },
  { value: "MP", label: "Madhya Pradesh" },
  { value: "MH", label: "Maharashtra" },
  { value: "MN", label: "Manipur" },
  { value: "ML", label: "Meghalaya" },
  { value: "MZ", label: "Mizoram" },
  { value: "NL", label: "Nagaland" },
  { value: "OD", label: "Odisha" },
  { value: "PY", label: "Puducherry" },
  { value: "PB", label: "Punjab" },
  { value: "RJ", label: "Rajasthan" },
  { value: "SK", label: "Sikkim" },
  { value: "TN", label: "Tamil Nadu" },
  { value: "TS", label: "Telangana" },
  { value: "TR", label: "Tripura" },
  { value: "UP", label: "Uttar Pradesh" },
  { value: "UK", label: "Uttarakhand" },
  { value: "WB", label: "West Bengal" },
];

export const CITIES_BY_STATE = {
  AN: ["Port Blair", "Bambooflat", "Garacharma", "Neil Island", "Havelock Island"],
  AP: [
    "Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Rajahmundry",
    "Tirupati", "Kakinada", "Kadapa", "Anantapur", "Eluru", "Ongole", "Chittoor",
    "Vizianagaram", "Tenali", "Proddatur", "Machilipatnam", "Adoni", "Nandyal",
    "Hindupur", "Srikakulam", "Bhimavaram", "Gudivada", "Madanapalle", "Guntakal",
  ],
  AR: ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro", "Bomdila", "Roing", "Aalo"],
  AS: [
    "Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tezpur", "Tinsukia",
    "Bongaigaon", "Karimganj", "Diphu", "Goalpara", "Barpeta", "Sivasagar",
    "Nalbari", "Dhulia", "Lakhimpur", "Hailakandi", "Kokrajhar", "Mangaldai", "North Lakhimpur",
  ],
  BR: [
    "Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga", "Purnia", "Arrah",
    "Begusarai", "Katihar", "Munger", "Chhapra", "Danapur", "Bihar Sharif",
    "Saharsa", "Hajipur", "Sasaram", "Dehri", "Siwan", "Motihari", "Nawada",
    "Bettiah", "Gopalganj", "Jamalpur", "Kishanganj", "Madhubani", "Samastipur", "Buxar",
  ],
  CH: ["Chandigarh", "Manimajra", "Sector 17", "Zirakpur"],
  CG: [
    "Raipur", "Bhilai", "Korba", "Bilaspur", "Durg", "Raigarh", "Rajnandgaon",
    "Jagdalpur", "Ambikapur", "Dhamtari", "Mahasamund", "Chirmiri", "Bhatapara",
    "Dalli-Rajhara", "Kawardha", "Sakti", "Manendragarh", "Baikunthpur",
  ],
  DD: ["Daman", "Diu", "Silvassa", "Vapi"],
  DL: [
    "New Delhi", "Delhi", "South Delhi", "North Delhi", "West Delhi", "East Delhi",
    "Central Delhi", "Rohini", "Dwarka", "Janakpuri", "Karol Bagh", "Lajpat Nagar",
    "Saket", "Vasant Kunj", "Pitampura", "Shahdara", "Narela", "Najafgarh",
    "Mehrauli", "Okhla", "Badarpur", "Ghitorni",
  ],
  GA: ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Bicholim", "Curchorem", "Candolim", "Calangute"],
  GJ: [
    "Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar",
    "Junagadh", "Gandhidham", "Anand", "Navsari", "Morbi", "Nadiad", "Surendranagar",
    "Bharuch", "Mehsana", "Bhuj", "Porbandar", "Palanpur", "Valsad", "Vapi",
    "Gondal", "Veraval", "Godhra", "Patan", "Kalol", "Dahod", "Amreli",
  ],
  HR: [
    "Faridabad", "Gurugram", "Panipat", "Ambala", "Yamunanagar", "Rohtak",
    "Hisar", "Karnal", "Sonipat", "Panchkula", "Bhiwani", "Sirsa", "Bahadurgarh",
    "Jind", "Thanesar", "Kaithal", "Rewari", "Palwal", "Hansi", "Narnaul",
    "Fatehabad", "Gohana", "Tohana", "Narwana", "Charkhi Dadri",
  ],
  HP: ["Shimla", "Manali", "Dharamshala", "Solan", "Mandi", "Kullu", "Bilaspur", "Hamirpur", "Una", "Palampur", "Nahan", "Kangra", "Sundarnagar", "Chamba"],
  JK: ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Udhampur", "Sopore", "Kathua", "Pulwama", "Rajouri", "Kupwara", "Poonch", "Bandipora"],
  JH: [
    "Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh", "Deoghar",
    "Giridih", "Ramgarh", "Medininagar", "Chirkunda", "Phusro", "Gumla",
    "Chaibasa", "Koderma", "Sahibganj", "Jhumri Telaiya", "Garhwa", "Lohardaga",
  ],
  KA: [
    "Bengaluru", "Mysuru", "Hubballi", "Mangaluru", "Belagavi", "Kalaburagi",
    "Davanagere", "Ballari", "Vijayapura", "Shivamogga", "Tumakuru", "Raichur",
    "Bidar", "Udupi", "Hospet", "Hassan", "Gadag", "Robertsonpet", "Kolar",
    "Mandya", "Chitradurga", "Chikkamagaluru", "Bagalkot", "Ranebennur",
    "Karwar", "Sirsi", "Madikeri", "Gangavathi", "Yadgir", "Chintamani",
  ],
  KL: [
    "Thiruvananthapuram", "Kochi", "Kozhikode", "Kollam", "Thrissur",
    "Palakkad", "Alappuzha", "Kannur", "Malappuram", "Kottayam", "Kasaragod",
    "Pathanamthitta", "Idukki", "Wayanad", "Varkala", "Guruvayur", "Ponnani",
    "Neyyattinkara", "Changanassery", "Chalakudy",
  ],
  LA: ["Leh", "Kargil"],
  LD: ["Kavaratti", "Agatti", "Minicoy", "Andrott", "Kalpeni"],
  MP: [
    "Indore", "Bhopal", "Gwalior", "Jabalpur", "Ujjain", "Sagar", "Dewas",
    "Satna", "Ratlam", "Rewa", "Murwara", "Singrauli", "Burhanpur", "Khandwa",
    "Morena", "Bhind", "Guna", "Chhindwara", "Vidisha", "Damoh", "Hoshangabad",
    "Mandsaur", "Neemuch", "Shivpuri", "Betul", "Sehore", "Datia", "Balaghat",
    "Panna", "Khargone", "Chhatarpur", "Tikamgarh", "Sidhi", "Sheopur",
  ],
  MH: [
    "Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur",
    "Amravati", "Kolhapur", "Sangli", "Malegaon", "Akola", "Latur", "Dhule",
    "Ahmednagar", "Chandrapur", "Parbhani", "Ichalkaranji", "Jalgaon", "Nanded",
    "Bhiwandi", "Ratnagiri", "Wardha", "Yavatmal", "Beed", "Gondia", "Satara",
    "Panvel", "Kalyan", "Vasai-Virar", "Navi Mumbai", "Mira-Bhayandar",
    "Ulhasnagar", "Karad", "Osmanabad", "Hingoli", "Washim", "Buldhana", "Akluj",
    "Pimpri-Chinchwad", "Shirdi", "Lonavala", "Alibag",
  ],
  MN: ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Senapati", "Ukhrul", "Kakching"],
  ML: ["Shillong", "Tura", "Nongstoin", "Jowai", "Baghmara", "Williamnagar", "Mairang"],
  MZ: ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib", "Saiha", "Lawngtlai"],
  NL: ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha", "Zunheboto", "Mon", "Phek", "Longleng"],
  OD: [
    "Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri",
    "Balasore", "Brahmapur", "Bhadrak", "Baripada", "Jharsuguda", "Jeypore",
    "Angul", "Koraput", "Dhenkanal", "Sundargarh", "Paradeep", "Rayagada",
    "Kendrapara", "Ganjam", "Nayagarh", "Keonjhar", "Phulbani", "Talcher",
  ],
  PY: ["Puducherry", "Karaikal", "Mahe", "Yanam", "Oulgaret"],
  PB: [
    "Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Pathankot",
    "Mohali", "Hoshiarpur", "Batala", "Moga", "Firozpur", "Kot Kapura",
    "Rajpura", "Abohar", "Barnala", "Khanna", "Malerkotla", "Sangrur",
    "Phagwara", "Muktsar", "Fazilka", "Kapurthala", "Nawanshahr", "Tarn Taran",
  ],
  RJ: [
    "Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer", "Udaipur", "Bhilwara",
    "Alwar", "Sikar", "Bharatpur", "Pali", "Sri Ganganagar", "Hanumangarh",
    "Tonk", "Kishangarh", "Beawar", "Sawai Madhopur", "Churu", "Dausa",
    "Sirohi", "Jhunjhunu", "Barmer", "Nagaur", "Jhalawar", "Chittorgarh",
    "Banswara", "Dholpur", "Ratangarh", "Makrana", "Hindaun", "Karauli",
  ],
  SK: ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Rangpo", "Singtam", "Jorethang"],
  TN: [
    "Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli",
    "Tiruppur", "Vellore", "Erode", "Thoothukkudi", "Dindigul", "Thanjavur",
    "Ranipet", "Sivakasi", "Karur", "Udhagamandalam", "Kancheepuram", "Hosur",
    "Nagercoil", "Kumbakonam", "Cuddalore", "Pudukkottai", "Karaikudi",
    "Nagapattinam", "Tiruvannamalai", "Pallavaram", "Tambaram", "Avadi",
    "Ambattur", "Kovilpatti", "Tiruchengode", "Ramanathapuram", "Villupuram",
    "Mayiladuthurai", "Sirkazhi",
  ],
  TS: [
    "Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Ramagundam",
    "Khammam", "Mahbubnagar", "Nalgonda", "Adilabad", "Siddipet", "Miryalaguda",
    "Suryapet", "Jagtial", "Kamareddy", "Koratla", "Mancherial", "Bhadrachalam",
    "Medak", "Sangareddy", "Vikarabad",
  ],
  TR: ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar", "Belonia", "Khowai", "Ambassa", "Sabroom"],
  UP: [
    "Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi", "Meerut", "Prayagraj",
    "Bareilly", "Aligarh", "Moradabad", "Saharanpur", "Gorakhpur", "Noida",
    "Jhansi", "Mathura", "Ayodhya", "Muzaffarnagar", "Raebareli", "Mirzapur",
    "Etawah", "Budaun", "Bulandshahr", "Hapur", "Firozabad", "Mainpuri",
    "Shahjahanpur", "Bijnor", "Amroha", "Sitapur", "Unnao", "Rampur", "Gonda",
    "Bahraich", "Lalitpur", "Orai", "Barabanki", "Kannauj", "Fatehpur",
    "Ghazipur", "Jaunpur", "Ballia", "Azamgarh", "Mau", "Faizabad", "Hardoi",
    "Pilibhit", "Etah", "Auraiya", "Kushinagar", "Deoria", "Chandauli",
    "Hamirpur", "Mahoba", "Banda", "Sonbhadra", "Sultanpur", "Amethi",
    "Pratapgarh", "Lakhimpur Kheri", "Basti", "Siddharthnagar",
  ],
  UK: [
    "Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rudrapur", "Kashipur",
    "Rishikesh", "Nainital", "Mussoorie", "Almora", "Pithoragarh", "Kotdwar",
    "Srinagar (Garhwal)", "Pauri", "Tehri", "Champawat", "Bageshwar", "Vikasnagar",
  ],
  WB: [
    "Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Bardhaman",
    "Malda", "Baharampur", "Habra", "Kharagpur", "Shantipur", "Dankuni",
    "Halisahar", "Barasat", "Krishnanagar", "Haldia", "Raiganj", "Jalpaiguri",
    "Midnapore", "Alipurduar", "Bankura", "Balurghat", "Darjeeling", "Cooch Behar",
    "Purulia", "Suri", "Rampurhat", "Tamluk", "Contai", "Chinsurah",
  ],
};
